name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    name: Zip & Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      ARCHIVE_NAME: UnequipAnyMods-${{ github.ref_name }}.zip

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: ${{ env.ARCHIVE_NAME }}
          exclusions: '*.git* /*node_modules/* README.md .editorconfig'

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: ${{ env.ARCHIVE_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
